### ISSUE TITLE
vswhere.exe does not return Installation Path of Visual Studio 2022 64bit Preview

### ISSUE THREAD

**Issue by d3c0d3d** [Enyium/vcvars-rs#1]
Look first thanks for your lib it helped save me a lot of time.
Unfortunately for it to work for me I had to make a change directly to the code as shown in the image below, I opened this issue just to inform.
![image](https://user-images.githubusercontent.com/29043805/216934070-bef9cd44-abf6-441a-bae2-87406d84bd66.png)

**Comment by Enyium** [comment]
Thank you for the information. Would you please try to add `"-prerelease", ` to the start of the `vswhere` switches *instead*?

Please tell whether you think it's okay to just allow preview versions regularly, or whether you're convinced they should be behind a flag passed to the `Vcvars` Rust type.

**Comment by d3c0d3d** [comment]
Thanks for the answer, the "-prerelease" parameter really works, it returns the same location of the image that I had posted before, well I think you should put an optional parameter in your library to be able to configure it, I myself only use the preview version because it has Constantly updates from VS which only has the preview version.
I leave it open, you decide, thank you!

**Comment by d3c0d3d** [comment]
#2
